spring.application.name=config-server
server.port=8888

# Active profile must be native
spring.profiles.active=native


# Point directly to the internal classpath folder
spring.cloud.config.server.native.search-locations=classpath:/config