# Bypass compatibility checks if it uses the same Spring Boot parent version
spring.cloud.compatibility-verifier.enabled=false
server.port=8080
# Connect Gateway to the Eureka Phonebook
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# --- ROUTING RULES ---

# Route 1: Product Service
spring.cloud.gateway.routes[0].id=product-service
spring.cloud.gateway.routes[0].uri=lb://PRODUCT-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/products/**

# Circuit breaker filter added below:
spring.cloud.gateway.routes[0].filters[0].name=CircuitBreaker
spring.cloud.gateway.routes[0].filters[0].args.name=productServiceCircuitBreaker
spring.cloud.gateway.routes[0].filters[0].args.fallbackUri=forward:/fallback/productServiceFallback
resilience4j.timelimiter.instances.productServiceCircuitBreaker.timeout-duration=5s

# Route 2: Order Service
spring.cloud.gateway.routes[1].id=order-service
spring.cloud.gateway.routes[1].uri=lb://ORDERSERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/orders/**

# Circuit breaker filter added below:
spring.cloud.gateway.routes[1].filters[0].name=CircuitBreaker
spring.cloud.gateway.routes[1].filters[0].args.name=orderServiceCircuitBreaker
spring.cloud.gateway.routes[1].filters[0].args.fallbackUri=forward:/fallback/orderServiceFallback
resilience4j.timelimiter.instances.orderServiceCircuitBreaker.timeout-duration=5s

# Tell micrometer to log and export 100% of traces to Zipkin
management.tracing.sampling.probability=1.0

# Point to your local Zipkin Docker container
management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans

# Tell Spring Security where to find Keycloak's public keys for JWT decoding
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:9090/realms/microservices-realm
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:9090/realms/microservices-realm/protocol/openid-connect/certs