
server.port=8083
# Broker Connection
spring.kafka.bootstrap-servers=127.0.0.1:9092

# 1. Use standard deserializers (No wrapper needed if we strip headers)
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

# 2. Force it to ignore the foreign class type headers sent by Order Service
spring.kafka.consumer.properties.spring.json.use.type.headers=false

# 3. PASTE YOUR EXACT CLASS PATH HERE BELOW:
# (Swap out 'com.example.notificationservice.dto' if your IDE shows a different package)
spring.kafka.consumer.properties.spring.json.value.default.type=com.example.notificationservice.notificationservice.Dto.OrderPlacedEvent

# Consumer Group configuration
spring.kafka.consumer.group-id=notification-group
spring.kafka.consumer.properties.spring.json.trusted.packages=*

# Timeouts stability
spring.kafka.consumer.properties.max.poll.interval.ms=600000
spring.kafka.consumer.properties.session.timeout.ms=90000
spring.kafka.consumer.properties.heartbeat.interval.ms=30000

# Eureka Client Configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# Tell micrometer to log and export 100% of traces to Zipkin
management.tracing.sampling.probability=1.0

# Point to your local Zipkin Docker container
management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans