# MongoDB Configuration
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.authentication-database=admin

server.port=8082

# Connection String Alternative (Simpler - use this instead of separate properties)

spring.data.mongodb.uri=mongodb://localhost:27017/OrderDb

# Optional MongoDB Settings
spring.data.mongodb.auto-index-creation=true

# Logging (to see MongoDB queries)
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
logging.level.org.mongodb.driver.protocol.command=DEBUG
spring.cloud.compatibility-verifier.enabled=false
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer


# Point to the direct local IP address
spring.kafka.bootstrap-servers=127.0.0.1:9092

# Producer Configuration
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
# Eureka Client Configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# Force Spring Boot to include trace and span information in the console logs
logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]

# Enable tracing exporting via web endpoints
management.tracing.enabled=true
management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans